### ISSUE TITLE
Bug in one line of the 2017 v11 file

### ISSUE THREAD

**Issue by jonquet** [sifrproject/cladimed2skos#1]
Per @elcioabrahao check for inconsistencies: 

Error on row: 1364
PrimaryEntry [f=E, sf=51, g=B, sg=G, ns=, code=E51BG00, label=ABANDON (ERREUR NUMÉROTATION) = E51B02, obs1=, obs2=, obs3=, rowNumber=1364, errorDescription=
Code data and code format are different]

**Comment by jonquet** [comment]
I have checked in a previous version of the .xls file that I have (v10) and this line is absent.
Therefore, I would suggest to just ignore this line (manually delete it) during the conversion process.

**Comment by elcioabrahao** [comment]
OK. Tks !
