### ISSUE TITLE
Metadata description for CLADIMED in SKOS

### ISSUE THREAD

**Issue by jonquet** [sifrproject/cladimed2skos#3]
We should include the following metadata in RDF/XML:

<rdf:Description rdf:about="http://cladimed.com/cladimed">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Ontology"/>
	<rdf:type rdf:resource="http://omv.ontoware.org/2005/05/ontology#Ontology"/>	
	
	
	<omv:name xml:lang="fr">Classification ClaDiMed</omv:name>
	<omv:name xml:lang="en">ClaDiMed Classification</omv:name>
	<omv:acronym>CLADIMED</omv:acronym>
	<omv:description xml:lang="fr">L’association CLADIMED a pour objet de favoriser, développer, mettre à disposition et promouvoir une classification des dispositifs médicaux. Ce travail, débuté il y a 10 ans déjà, est mené à bien par un groupe de professionnels bénévoles. L’association ne bénéficie d’aucune subvention ni soutien financier de quelque sorte. Elle est financée uniquement par la cotisation de ses adhérents.</omv:description>
	<omv:documentation>http://www.cladimed.com</omv:documentation>
	<omv:notes> Version SKOS produite par le LIRMM (@jonquet and @elcioabrahao) </omv:notes>
	<foaf:logo rdf:resource="http://www.cladimed.com/cladimed/wp-content/uploads/2013/11/cropped-LogoClaDiMed2-e13858328552231.jpg"/>
	<cc:morePermissions>Une version « simple » de la classification est distribuée librement, sur demande. Les adhérents à CLADIMED, reçoivent chaque année la dernière mise à jour de la classification avec le détail des évolutions (ajout, suppressions, remplacement modification) afin de faciliter sa mise en œuvre.</cc:morePermissions>
	<omv:reference>https://doi.org/10.1016/j.pharma.2011.06.006</omv:reference> 
	<foaf:homePage>http://www.cladimed.com</foaf:homePage>
	
	
	<omv:naturalLanguage rdf:resource="http://lexvo.org/id/iso639-3/fra"/>
	
	
	<omv:keywords> Dispositif médical </omv:keywords>
	
	
	<omv:creationDate rdf:datatype="xsd:dateTime"> 2007 </omv:creationDate>
	<omv:modificationDate rdf:datatype="xsd:dateTime">2017-01</omv:modificationDate>
	<dcterms:valid rdf:datatype="xsd:dateTime">2018-01</dcterms:valid>
	
	
	<omv:hasCreator>Association ClaDiMed </omv:hasCreator>
	<omv:hasContributor> Maurice Ventura </omv:hasContributor>
	<omv:hasFormalityLevel rdf:resource="http://omv.ontoware.org/2005/05/ontology#Vocabulary"/>
	<omv:hasOntologyLanguage> SKOS </omv:hasOntologyLanguage>
	<dcterms:publisher> Association ClaDiMed </dcterms:publisher>
	<omv:hasOntologySyntax rdf:resource="http://www.w3.org/ns/formats/RDF_XML"/>
	<omv:endorsedBy> Association ClaDiMed </omv:endorsedBy>

	
	<omv:status> production </omv:status>
	<omv:version> v11 </omv:version>
	<owl:versionInfo> Commentaire sur cette version</owl:versionInfo> 
	<owl:versionIRI rdf:resource="http://cladimed.com/cladimed/2017/v11"/>
	<vann:example rdf:resource="http://cladimed.com/cladimed#R57CA04"/>

	
	<omv:hasPriorVersion rdf:resource="http://cladimed.com/cladimed/2016/v10"/>
	<dcterms:isFormatOf> XLS version </dcterms:isFormatOf>

	<prov:wasGeneratedBy rdf:resource="https://github.com/sifrproject/cladimed2skos"/>
</rdf:Description>

**Comment by elcioabrahao** [comment]
Added !
